apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant.fullname" . }}
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tenant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tenant.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "tenant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRPC_PORT
              value: "{{ .Values.pod.grpcport }}"
            - name: HTTPS_PORT
              value: "{{ .Values.pod.httpsport }}"
            - name: DATABASE_CONNECTION_STRING
              value: "{{ .Values.pod.database.connection_string }}"
            - name: TENANT_DATABASE_NAME
              value: "{{ .Values.pod.database.name }}"
          ports:
            - name: grpc
              containerPort: {{ .Values.pod.grpcport }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.pod.httpsport }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: https
          readinessProbe:
            httpGet:
              path: /ready
              port: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
